name: Test Action

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '*/37 12 * * *'

jobs:
  ghcr:
    runs-on: ubuntu-latest
    env:
      TEST_REGISTRY: ghcr.io
      TEST_REPOSITORY: ${{ github.repository }}-test
      TEST_TAG: ${{ github.run_id }}
      TEST_IMAGE: ghcr.io/${{ github.repository }}-test:${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - run: |
        docker pull hello-world
        docker tag hello-world $TEST_IMAGE
        docker push $TEST_IMAGE
    - name: Add One Tag
      uses: ./
      with:
        registry: ghcr.io
        token: ${{ secrets.GHCR_PAT }}
        repository: ${{ env.TEST_REPOSITORY }}
        target: ${{ env.TEST_TAG }}
        tags: single
    - name: Add Multiple Tags
      uses: ./
      with:
        registry: ghcr.io
        token: ${{ secrets.GHCR_PAT }}
        repository: ${{ env.TEST_REPOSITORY }}
        target: ${{ env.TEST_TAG }}
        tags: |
          multiple-a
          multiple-b
    - name: Assert Image Has Tags
      run: |
        echo "::group::Assertions"
        TAGS=('single' 'multiple-a' 'multiple-b')
        for test_tag in "${TAGS[@]}"
          image=$TEST_REGISTRY/$TEST_REPOSITORY:$test_tag
          if docker manifest inspect $image >/dev/null; then
            echo "::debug::$test_tag found, test passed"
          else
            echo "::error::$test_tag not found, test failed"
          fi
        echo "::endgroup::"
    - name: Clean Up Image
      if: always()
      run: docker rmi --force $TEST_IMAGE
