name: Integration Test

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "*/37 12 * * *"

jobs:
  tag-example-image:
    runs-on: ubuntu-latest
    env:
      TEST_REGISTRY: ghcr.io
      TEST_REPOSITORY: "${{ github.repository }}-test"
      TEST_TAG: "${{ github.run_id }}"
      TEST_IMAGE: "ghcr.io/${{ github.repository }}-test:${{ github.run_id }}"
    steps:
      - uses: actions/checkout@v2
      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GHCR_PAT }}"
      - name: Add example image to container registry for test repository
        run: |
          docker pull hello-world
          docker tag hello-world $TEST_IMAGE
          docker push $TEST_IMAGE
      - name: Add One Tag
        uses: ./
        with:
          registry: ghcr.io
          token: "${{ secrets.GHCR_PAT }}"
          repository: "${{ env.TEST_REPOSITORY }}"
          target: "${{ env.TEST_TAG }}"
          tags: "${{ github.run_id }}-single"
      - name: Add Multiple Tags
        uses: ./
        with:
          registry: ghcr.io
          token: "${{ secrets.GHCR_PAT }}"
          repository: "${{ env.TEST_REPOSITORY }}"
          target: "${{ env.TEST_TAG }}"
          tags: |
            ${{ github.run_id }}-multiple-a
            ${{ github.run_id }}-multiple-b
  assert-tags-exist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [single, multiple-a, multiple-b, not-found]
      fail-fast: false
    env:
      repository: "https://ghcr.io/v2/${{ github.repository }}-test"
      tag: "${{ github.run_id }}-${{ matrix.tag }}"
    steps:
      - name: Assert image has tag ${{ matrix.tag }}
        run: |
          token=$(echo ${{ secrets.GHCR_PAT }} | base64)
          curl -i $repository/manifests/$tag -H 'Authorization: Bearer $token'
