name: "Test Action (Unit)"

on:
  push:
    branches:
      - "**"

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - name: Execute unit tests
        run: npm run test
