name: Test Action

on:
  push:
    branches:
      - '**'
  schedule:
    - cron: '*/37 12 * * *'

jobs:
  ghcr:
    runs-on: ubuntu-latest
    env:
      TEST_REGISTRY: ghcr.io
      TEST_REPOSITORY: ${{ github.repository }}-test
      TEST_TAG: ${{ github.run_id }}
      TEST_IMAGE: ghcr.io/${{ github.repository }}-test:${{ github.run_id }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
    - run: |
        docker pull hello-world
        docker tag hello-world $TEST_IMAGE
        docker push $TEST_IMAGE
    - name: Add One Tag
      uses: ./
      with:
        registry: ghcr.io
        token: ${{ secrets.GHCR_PAT }}
        repository: ${{ env.TEST_REPOSITORY }}
        target: ${{ env.TEST_TAG }}
        tags: ${{ github.run_id }}-single
    - name: Add Multiple Tags
      uses: ./
      with:
        registry: ghcr.io
        token: ${{ secrets.GHCR_PAT }}
        repository: ${{ env.TEST_REPOSITORY }}
        target: ${{ env.TEST_TAG }}
        tags: |
          ${{ github.run_id }}-multiple-a
          ${{ github.run_id }}-multiple-b
    - name: Assert Image Has Tags
      run: |
        TAGS=('single' 'multiple-a' 'multiple-b')
        for tag in "${TAGS[@]}"
        do
          IMAGE="${TEST_IMAGE}-${tag}"
          if docker manifest inspect $IMAGE >/dev/null; then
            echo "pass: $IMAGE found"
          else
            echo "fail: $IMAGE not found"
            echo "::error::$IMAGE not found, test failed"
          fi
        done
